services:
  app:
    restart: always
    init: true
    build:
      context: ./
      dockerfile: ./docker/apache/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./data/app:/data
    environment:
      - APP_ENV=${APP_ENV:-production}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@feedbackie.app}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
      - ADMIN_PATH=${ADMIN_PATH:-admin}
      - DB_HOST=${DB_HOST:-}
      - DB_PORT=${DB_PORT:-}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - DB_USERNAME=${DB_USERNAME:-}
      - DB_CONNECTION=${DB_CONNECTION:-sqlite}
      - MAIL_USERNAME=${SMTP_USER:-}
      - MAIL_HOST=${SMTP_HOST:-}
      - MAIL_PORT=${SMTP_PORT:-}
      - MAIL_PASSWORD=${SMTP_PASSWORD:-}
